version: '3'

services:
  yourls_db:
    image: mysql:5.7
    container_name: yourls_db
    restart: always
    ports:
     - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yourls

  yourls:
    image: yourls
    container_name: yourls_app
    restart: always
    depends_on:
     - yourls_db
    ports:
     - 8080:80
    volumes:
      - yourls_data:/var/www/html
    environment:
      YOURLS_DB_HOST: yourls_db:3306
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: root
      YOURLS_DB_NAME: yourls
      YOURLS_URL_CONVERT: 36
      YOURLS_HOURS_OFFSET: +8
      YOURLS_SITE: http://localhost:8080
      YOURLS_USER: admin
      YOURLS_PASS: admin
#      VIRTUAL_HOST: go.einverne.info
#      VIRTUAL_PORT: 8080
#      LETSENCRYPT_HOST: go.einverne.info
#      LETSENCRYPT_EMAIL: admin@einverne.info

volumes:
  db_data:
  yourls_data:
